### PR TITLE
Demos package

### PR DESCRIPTION
**Pull request by chapulina**
Add a package with demo launch files which show how to use various sensor types. See READMEs for more info. 

Currently covered sensors:

* camera
* depth camera
* IMU
* magnetometer
* RGBD camera
* GPU lidar

### CODE REVIEW

**Comment by caguero** [comment]
I got this error when launching the RGBD camera example:

`[Err] [SystemLoader.cc:66] Failed to load system plugin [libRos1IgnPointCloud.so] : couldn't find shared library.
[Err] [SystemLoader.cc:66] Failed to load system plugin [libRos1IgnPointCloud.so] : couldn't find shared library.`

Is it expected?

**Comment by chapulina** [comment]
> I got this error when launching the RGBD camera example

I had just noticed that as well, my local setup automatically sets the paths. This should fix it: 60496e2b0db9ab83d18bd3febc70a3ed1facc06a

**Comment by caguero** [comment]
While running the RGBD camera example, `rviz` shows the pointcloud in the scene OK, the image from the `/rgbd_camera/image` topic OK but the image from the `/rgbd_camera/depth_image` looks black. Can you see the depth image?

**Comment by chapulina** [comment]
Oh sorry I forgot to mention it again in this PR. The depth images need https://github.com/ros-visualization/rviz/pull/1378 to show properly on RViz

**Comment by caguero** [comment]
Approving!

**Pull request merged**
