### PR TITLE
.travis/build: rosdep skip ignition keys

### PR DESCRIPTION
**Pull request by IeiuniumLux**
to fix the rosdep issue in #17

### CODE REVIEW

**Comment by chapulina** [comment]
Thanks! This works for me, we just need to skip all the ign libs

**Comment by scpeters** [comment]
Thanks to @jacobperron for the advice

**Comment by scpeters** [comment]
I'll add the missing packages

**Comment by azeey** [comment]
Nice! Didn't know about `skip-keys`.

**Pull request merged**
